### ISSUE TITLE
Enable SemaphoreCI

### ISSUE THREAD

**Issue by ghousemohamed** [bigbinary/neeto-email-prefixer#7]
cc: @Nuzair46

**Comment by Nuzair46** [comment]
@ghousemohamed _a, semaphore config seems to be alright. I don't have permissions to setup semaphoreci for this repo in the web app.

**Comment by sumanranjanpanda** [comment]
@ghousemohamed Can you please look into this and close this issue asap?

**Comment by ghousemohamed** [comment]
@vishal24367 Can we setup neetoCI for this repository?

**Comment by vishal24367** [comment]
@ghousemohamed Sure, will add this repository to the neetoCI.

**Comment by vishal24367** [comment]
@ghousemohamed Sure, will add this repository to the neetoCI.
